### ISSUE TITLE
Issues partnert

### ISSUE THREAD

**Issue by robertch2283** [Emmigumi/trivia-add-repo#1]
*La ortografía no es la correcta, en todas dice: Inconrrecto, en las 3 respuestas

*Importar librería time

**Comment by Emmigumi** [comment]
Observaciones levantadas, adjunto link donde se visualizan los cambios.
[Commit: Isuues#1](https://github.com/Emmigumi/trivia-add-repo/commit/bb48a71be848a5cbf9ea63643e562640a9710795)
